# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha publicacion'),
        ),
    ]
